CFLAGS += -I $(TOPDIR)	\
		  -I $(CLI_INC_DIR)/common	\
		  -I $(CLI_INC_DIR)/common/util \
		  -I $(CLI_INC_DIR)/common/print \
		  -I $(CLI_INC_DIR)/common/util \
		  -I $(CLI_INC_DIR)/common/vfs \
		  -I $(CLI_INC_DIR)/module	\
		  -I $(CLI_INC_DIR)/module/filetrans \
		  -I $(CLI_INC_DIR)/core
		  
		  
obj-y += bc_cli_acc.o		  
obj-y += bc_cli_alias.o		  
obj-y += bc_cli_api.o
obj-y += bc_cli_bnr.o		
obj-y += bc_cli_bnr_cmd.o	
obj-y += bc_cli_bnr_stk.o	
obj-y += bc_cli_chs.o
obj-y += bc_cli_core.o	
obj-y += bc_cli_db.o
obj-y += bc_cli_dir.o
obj-y += bc_cli_edit.o
obj-y += bc_cli_fltr.o
obj-y += bc_cli_hist.o
obj-y += bc_cli_hook.o
obj-y += bc_cli_io.o
#obj-y += bc_cli_ipc.o		  
obj-y += bc_cli_log_cmd.o
obj-y += bc_cli_mainprocess.o		  
obj-y += bc_cli_misc.o
obj-y += bc_cli_para.o	
obj-y += bc_cli_parse.o
obj-y += bc_cli_prt.o	
#obj-y += bc_cli_pseudo.o
obj-y += bc_cli_sesn.o
obj-y += bc_cli_sys_cmd.o
obj-y += bc_cli_vio.o
obj-y += bc_cli_vt100.o
obj-y += vt_100.o