CFLAGS += -I $(BC_INC_DIR)/common	\
		  -I $(BC_INC_DIR)/common/error	\
		  -I $(BC_INC_DIR)/common/modules	\
		  -I $(BC_INC_DIR)/common/nouse	\
		  -I $(BC_INC_DIR)/common/ipc	\
		  -I $(BC_INC_DIR)/common/platform	\
		  -I $(BC_INC_DIR)/common/print	\
		  -I $(BC_INC_DIR)/common/vfs	\
		  -I $(BC_INC_DIR)/common/log	\
		  -I $(BC_INC_DIR)/common/util	\
		  -I $(BC_INC_DIR)/common/message	\
		  -I $(BC_INC_DIR)/module/system/baseinfo	\
		  -I $(BC_INC_DIR)/module/system/ipc	\
		  -I $(BC_INC_DIR)/module/system/platform	\
		  -I $(BC_INC_DIR)/module/system/session	\
		  -I $(BC_INC_DIR)/module/system/log	\
		  -I $(BC_INC_DIR)/proj

CFLAGS += -I $(CLI_INC_DIR)	
		  
  
OBJECT = bc_cli_alias.o \
		bc_cli_api.o \
		bc_cli_bnr.o \
		bc_cli_chs.o \
		bc_cli_cmd_bnr.o \
		bc_cli_cmd_log.o \
		bc_cli_cmd_sys.o \
		bc_cli_core.o \
		bc_cli_db.o \
		bc_cli_dir.o \
		bc_cli_edit.o \
		bc_cli_fltr.o \
		bc_cli_hist.o \
		bc_cli_hook.o \
		bc_cli_mainprocess.o \
		bc_cli_misc.o \
		bc_cli_para.o \
		bc_cli_para_lex_dnf.o \
		bc_cli_parse.o \
		bc_cli_pseudo.o \
		bc_cli_sesn.o \
		bc_cli_utili_print.o \
		bc_cli_vio.o

obj-y += $(OBJECT)