CFLAGS += -I $(TOPDIR)	\
		  -I $(BC_INC_DIR_COMMON)	\
		  -I $(BC_INC_DIR_COMMON)/error	\
		  -I $(BC_INC_DIR_COMMON)/modules	\
		  -I $(BC_INC_DIR_COMMON)/ipc	\
		  -I $(BC_INC_DIR_COMMON)/nouse	\
		  -I $(BC_INC_DIR_COMMON)/platform	\
		  -I $(BC_INC_DIR_COMMON)/print	\
		  -I $(BC_INC_DIR_COMMON)/vfs	\
		  -I $(BC_INC_DIR_COMMON)/log	\
		  -I $(BC_INC_DIR_COMMON)/util	\
		  -I $(BC_INC_DIR_COMMON)/message	\
		  -I $(BC_INC_DIR_PROJ)				\
		  -I $(MODULEDIR)/L2mc			\
		  -I $(MODULEDIR)/L2mc/drv		\
		  -I $(MODULEDIR)/L2mc/igmpsnp/util/inc	\
		  -I $(MODULEDIR)/L2mc/igmpsnp/mcast/inc
		  
		  
OBJECT = mcast_call.o \
			mcast_cfg.o \
			mcast_cfg_grp.o \
			mcast_core.o \
			mcast_host.o \
			mcast_init.o \
			mcast_mgmt.o \
			mcast_pkt.o \
			mcast_router.o \
			mcast_rx.o \
			mcast_tx.o \
			mcast_utl.o
			
obj-y += $(OBJECT)