CFLAGS += -I $(TOPDIR)	\
		  -I $(CLI_INC_DIR)/common	\
		  -I $(CLI_INC_DIR)/common/platform \
		  -I $(CLI_INC_DIR)/common/util \
		  -I $(CLI_INC_DIR)/common/print \
		  -I $(CLI_INC_DIR)/common/vfs \
		  -I $(CLI_INC_DIR)/module	\
		  -I $(CLI_INC_DIR)/module/filetrans \
		  -I $(CLI_INC_DIR)/core
		  

obj-y += bc_platform_init.o
obj-y += bc_platform_mem.o
obj-y += bc_platform_mutex.o
obj-y += bc_platform_procps.o
obj-y += bc_platform_queue.o
obj-y += bc_platform_sem.o
obj-y += bc_platform_signal.o
obj-y += bc_platform_thread.o
obj-y += bc_platform_time.o