/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef FHVCTRAPS_H
#define FHVCTRAPS_H
#include "snmp_trap_comm.h"

/* function declarations */
int send_fhVCDown_trap(snmp_alarm_info_t alarm_info);
int send_fhVCUp_trap(snmp_alarm_info_t alarm_info);
int send_fhPwe3VCW2P_trap(snmp_alarm_info_t alarm_info);
int send_fhPwe3VCP2W_trap(snmp_alarm_info_t alarm_info);

#if SNMP_PRJ_NAME_610A
#include "mBase.h"
#include "event/event_eth_port.h"
#include "mpapi.h"
#include "comm/lr_errors.h"

#endif

#endif /* FHVCTRAPS_H */
