/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef FHINTFTRAPS_H
#define FHINTFTRAPS_H
#include "snmp_trap_comm.h"

/* function declarations */
int send_fhIntfTrafficExceed_trap(snmp_alarm_info_t alarm_info);
int send_fhIntfRxBadPktExceed_trap(snmp_alarm_info_t alarm_info);
int send_fhPhysicalInterfaceDown_trap(snmp_alarm_info_t alarm_info);

#if SNMP_PRJ_NAME_610A
#include "mBase.h"
#include "event/event_eth_port.h"
#include "mpapi.h"
#include "comm/lr_errors.h"

bc_boolean alarm_proc_dev_port(
											eventNotifyRes *resData, 
											struct event_bitmap event,
											struct mBase_client *client, 
											snmp_alarm_info_t alarm_info
										);
#endif

#endif /* FHINTFTRAPS_H */
