/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef TESTTRAPS_H
#define TESTTRAPS_H

/* function declarations */
int send_cpuRatioHigh_trap(void);

#endif /* TESTTRAPS_H */
