CFLAGS += -I $(TOPDIR)	\
		  -I $(CLI_INC_DIR)/common	\
		  -I $(CLI_INC_DIR)/common/util \
		  -I $(CLI_INC_DIR)/common/print \
		  -I $(CLI_INC_DIR)/common/util \
		  -I $(CLI_INC_DIR)/common/vfs \
		  -I $(CLI_INC_DIR)/module	\
		  -I $(CLI_INC_DIR)/module/filetrans \
		  -I $(CLI_INC_DIR)/core


obj-y += platform/
obj-y += print/
obj-y += util/
obj-y += vfs/
obj-y += bc_modules.o