/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "snmp_trap_fhVCTraps.h"
#include "snmp_trap_comm.h"
#include "snmp_global.h"
#include "snmp_core_ex.h"


extern const oid snmptrap_oid[];
extern const size_t snmptrap_oid_len;

int
send_fhVCDown_trap( snmp_alarm_info_t alarm_info )
{
    netsnmp_variable_list  *var_list = NULL;
    const oid fhVCDown_oid[] = { 1,3,6,1,4,1,11408,11,1,6,4,1,1 };
    const oid VcId_oid[] = { 1,3,6,1,4,1,11408,11,1,6,2,1,1,6,  };
    const oid VcType_oid[] = { 1,3,6,1,4,1,11408,11,1,6,2,1,1,1,  };
    const oid PeerAddress_oid[] = { 1,3,6,1,4,1,11408,11,1,6,2,1,1,5,  };
    const oid CtrlWord_oid[] = { 1,3,6,1,4,1,11408,11,1,6,2,1,1,2,  };
    const oid SecondaryPwId_oid[] = { 1,3,6,1,4,1,11408,11,1,6,2,1,1,3,  };
    const oid ifName_oid[] = { 1,3,6,1,4,1,11408,11,1,2,2,0,0,1,  };

    snmp_varlist_add_variable(&var_list,
        snmptrap_oid, snmptrap_oid_len,
        ASN_OBJECT_ID,
        fhVCDown_oid, sizeof(fhVCDown_oid));

    snmp_varlist_add_variable(&var_list,
        VcId_oid, OID_LENGTH(VcId_oid),
        ASN_INTEGER,
        (u_char *)&alarm_info.vc_info.vd_id, sizeof(alarm_info.vc_info.vd_id));
	
    snmp_varlist_add_variable(&var_list,
        VcType_oid, OID_LENGTH(VcType_oid),
        ASN_INTEGER,
        (u_char *)&alarm_info.vc_info.vc_type, sizeof(alarm_info.vc_info.vc_type));
	
    snmp_varlist_add_variable(&var_list,
        PeerAddress_oid, OID_LENGTH(PeerAddress_oid),
        ASN_IPADDRESS,
        (u_char *)&alarm_info.vc_info.peer_addr, sizeof(alarm_info.vc_info.peer_addr));
	
    snmp_varlist_add_variable(&var_list,
        CtrlWord_oid, OID_LENGTH(CtrlWord_oid),
        ASN_INTEGER,
        (u_char *)&alarm_info.vc_info.ctrl_word, sizeof(alarm_info.vc_info.ctrl_word));
	
    snmp_varlist_add_variable(&var_list,
        SecondaryPwId_oid, OID_LENGTH(SecondaryPwId_oid),
        ASN_INTEGER,
        (u_char *)&alarm_info.vc_info.second_pw_id, sizeof(alarm_info.vc_info.second_pw_id));
	
    snmp_varlist_add_variable(&var_list,
        ifName_oid, OID_LENGTH(ifName_oid),
        ASN_OCTET_STR,
        (u_char *)alarm_info.vc_info.ifname, strlen(alarm_info.vc_info.ifname));

    send_v2trap( var_list );
    snmp_free_varbind( var_list );

    return SNMP_ERR_NOERROR;
}
int
send_fhVCUp_trap( snmp_alarm_info_t alarm_info )
{
    netsnmp_variable_list  *var_list = NULL;
    const oid fhVCUp_oid[] = { 1,3,6,1,4,1,11408,11,1,6,4,1,2 };
    const oid VcId_oid[] = { 1,3,6,1,4,1,11408,11,1,6,2,1,1,6,  };
    const oid VcType_oid[] = { 1,3,6,1,4,1,11408,11,1,6,2,1,1,1,  };
    const oid PeerAddress_oid[] = { 1,3,6,1,4,1,11408,11,1,6,2,1,1,5,  };
    const oid CtrlWord_oid[] = { 1,3,6,1,4,1,11408,11,1,6,2,1,1,2,  };
    const oid PrimaryPwId_oid[] = { 1,3,6,1,4,1,11408,11,1,6,2,1,1,4,  };
    const oid ifName_oid[] = { 1,3,6,1,4,1,11408,11,1,2,2,0,0,1,  };

    snmp_varlist_add_variable(&var_list,
        snmptrap_oid, snmptrap_oid_len,
        ASN_OBJECT_ID,
        fhVCUp_oid, sizeof(fhVCUp_oid));

    snmp_varlist_add_variable(&var_list,
        VcId_oid, OID_LENGTH(VcId_oid),
        ASN_INTEGER,
        (u_char *)&alarm_info.vc_info.vd_id, sizeof(alarm_info.vc_info.vd_id));
	
    snmp_varlist_add_variable(&var_list,
        VcType_oid, OID_LENGTH(VcType_oid),
        ASN_INTEGER,
        (u_char *)&alarm_info.vc_info.vc_type, sizeof(alarm_info.vc_info.vc_type));
	
    snmp_varlist_add_variable(&var_list,
        PeerAddress_oid, OID_LENGTH(PeerAddress_oid),
        ASN_IPADDRESS,
        (u_char *)&alarm_info.vc_info.peer_addr, sizeof(alarm_info.vc_info.peer_addr));
	
    snmp_varlist_add_variable(&var_list,
        CtrlWord_oid, OID_LENGTH(CtrlWord_oid),
        ASN_INTEGER,
        (u_char *)&alarm_info.vc_info.ctrl_word, sizeof(alarm_info.vc_info.ctrl_word));
	
    snmp_varlist_add_variable(&var_list,
        PrimaryPwId_oid, OID_LENGTH(PrimaryPwId_oid),
        ASN_INTEGER,
        (u_char *)&alarm_info.vc_info.primary_pw_id, sizeof(alarm_info.vc_info.primary_pw_id));
	
    snmp_varlist_add_variable(&var_list,
        ifName_oid, OID_LENGTH(ifName_oid),
        ASN_OCTET_STR,
        (u_char *)alarm_info.vc_info.ifname, strlen(alarm_info.vc_info.ifname));

    send_v2trap( var_list );
    snmp_free_varbind( var_list );

    return SNMP_ERR_NOERROR;
}
int
send_fhPwe3VCW2P_trap( snmp_alarm_info_t alarm_info )
{
    netsnmp_variable_list  *var_list = NULL;
    const oid fhPwe3VCW2P_oid[] = { 1,3,6,1,4,1,11408,11,1,6,4,2,1 };
    const oid VcId_oid[] = { 1,3,6,1,4,1,11408,11,1,6,2,1,1,6,  };
    const oid VcType_oid[] = { 1,3,6,1,4,1,11408,11,1,6,2,1,1,1,  };
    const oid PeerAddress_oid[] = { 1,3,6,1,4,1,11408,11,1,6,2,1,1,5,  };
    const oid CtrlWord_oid[] = { 1,3,6,1,4,1,11408,11,1,6,2,1,1,2,  };
    const oid SecondaryPwId_oid[] = { 1,3,6,1,4,1,11408,11,1,6,2,1,1,3,  };
    const oid ifName_oid[] = { 1,3,6,1,4,1,11408,11,1,2,2,0,0,1,  };

    snmp_varlist_add_variable(&var_list,
        snmptrap_oid, snmptrap_oid_len,
        ASN_OBJECT_ID,
        fhPwe3VCW2P_oid, sizeof(fhPwe3VCW2P_oid));

    snmp_varlist_add_variable(&var_list,
        VcId_oid, OID_LENGTH(VcId_oid),
        ASN_INTEGER,
        (u_char *)&alarm_info.vc_info.vd_id, sizeof(alarm_info.vc_info.vd_id));
	
    snmp_varlist_add_variable(&var_list,
        VcType_oid, OID_LENGTH(VcType_oid),
        ASN_INTEGER,
        (u_char *)&alarm_info.vc_info.vc_type, sizeof(alarm_info.vc_info.vc_type));
	
    snmp_varlist_add_variable(&var_list,
        PeerAddress_oid, OID_LENGTH(PeerAddress_oid),
        ASN_IPADDRESS,
        (u_char *)&alarm_info.vc_info.peer_addr, sizeof(alarm_info.vc_info.peer_addr));
	
    snmp_varlist_add_variable(&var_list,
        CtrlWord_oid, OID_LENGTH(CtrlWord_oid),
        ASN_INTEGER,
        (u_char *)&alarm_info.vc_info.ctrl_word, sizeof(alarm_info.vc_info.ctrl_word));
	
    snmp_varlist_add_variable(&var_list,
        SecondaryPwId_oid, OID_LENGTH(SecondaryPwId_oid),
        ASN_INTEGER,
        (u_char *)&alarm_info.vc_info.second_pw_id, sizeof(alarm_info.vc_info.second_pw_id));
	
    snmp_varlist_add_variable(&var_list,
        ifName_oid, OID_LENGTH(ifName_oid),
        ASN_OCTET_STR,
        (u_char *)alarm_info.vc_info.ifname, strlen(alarm_info.vc_info.ifname));

    send_v2trap( var_list );
    snmp_free_varbind( var_list );

    return SNMP_ERR_NOERROR;
}
int
send_fhPwe3VCP2W_trap( snmp_alarm_info_t alarm_info )
{
    netsnmp_variable_list  *var_list = NULL;
    const oid fhPwe3VCP2W_oid[] = { 1,3,6,1,4,1,11408,11,1,6,4,2,2 };
    const oid VcId_oid[] = { 1,3,6,1,4,1,11408,11,1,6,2,1,1,6,  };
    const oid VcType_oid[] = { 1,3,6,1,4,1,11408,11,1,6,2,1,1,1,  };
    const oid PeerAddress_oid[] = { 1,3,6,1,4,1,11408,11,1,6,2,1,1,5,  };
    const oid CtrlWord_oid[] = { 1,3,6,1,4,1,11408,11,1,6,2,1,1,2,  };
    const oid PrimaryPwId_oid[] = { 1,3,6,1,4,1,11408,11,1,6,2,1,1,4,  };
    const oid ifName_oid[] = { 1,3,6,1,4,1,11408,11,1,2,2,0,0,1,  };

    snmp_varlist_add_variable(&var_list,
        snmptrap_oid, snmptrap_oid_len,
        ASN_OBJECT_ID,
        fhPwe3VCP2W_oid, sizeof(fhPwe3VCP2W_oid));

    snmp_varlist_add_variable(&var_list,
        VcId_oid, OID_LENGTH(VcId_oid),
        ASN_INTEGER,
        (u_char *)&alarm_info.vc_info.vd_id, sizeof(alarm_info.vc_info.vd_id));
	
    snmp_varlist_add_variable(&var_list,
        VcType_oid, OID_LENGTH(VcType_oid),
        ASN_INTEGER,
        (u_char *)&alarm_info.vc_info.vc_type, sizeof(alarm_info.vc_info.vc_type));
	
    snmp_varlist_add_variable(&var_list,
        PeerAddress_oid, OID_LENGTH(PeerAddress_oid),
        ASN_IPADDRESS,
        (u_char *)&alarm_info.vc_info.peer_addr, sizeof(alarm_info.vc_info.peer_addr));
	
    snmp_varlist_add_variable(&var_list,
        CtrlWord_oid, OID_LENGTH(CtrlWord_oid),
        ASN_INTEGER,
        (u_char *)&alarm_info.vc_info.ctrl_word, sizeof(alarm_info.vc_info.ctrl_word));
	
    snmp_varlist_add_variable(&var_list,
        PrimaryPwId_oid, OID_LENGTH(PrimaryPwId_oid),
        ASN_INTEGER,
        (u_char *)&alarm_info.vc_info.primary_pw_id, sizeof(alarm_info.vc_info.primary_pw_id));
	
    snmp_varlist_add_variable(&var_list,
        ifName_oid, OID_LENGTH(ifName_oid),
        ASN_OCTET_STR,
        (u_char *)alarm_info.vc_info.ifname, strlen(alarm_info.vc_info.ifname));

    send_v2trap( var_list );
    snmp_free_varbind( var_list );

    return SNMP_ERR_NOERROR;
}

#if SNMP_PRJ_NAME_610A
#include "mBase.h"
#include "event/event_eth_port.h"
#include "mpapi.h"
#include "comm/lr_errors.h"

#endif
