/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "snmp_trap_fhIntfTraps.h"
#include "snmp_trap_comm.h"
#include "snmp_global.h"
#include "snmp_core_ex.h"

#include "bc_common_defs.h"


extern const oid snmptrap_oid[];
extern const size_t snmptrap_oid_len;

int
send_fhIntfTrafficExceed_trap( snmp_alarm_info_t alarm_info )
{
    netsnmp_variable_list  *var_list = NULL;
    const oid fhIntfTrafficExceed_oid[] = { 1,3,6,1,4,1,11408,11,1,2,3,1,1};
    const oid ifName_oid[] = { 1,3,6,1,4,1,11408,11,1,2,2,0,0,1};
    const oid ifIndex_oid[] = { 1,3,6,1,4,1,11408,11,1,2,2,0,0,2};
    const oid ifInputRate_oid[] = { 1,3,6,1,4,1,11408,11,1,2,2,0,0,8};
    const oid ifOutputRate_oid[] = { 1,3,6,1,4,1,11408,11,1,2,2,0,0,9};

    snmp_varlist_add_variable(&var_list,
        snmptrap_oid, snmptrap_oid_len,
        ASN_OBJECT_ID,
        fhIntfTrafficExceed_oid, sizeof(fhIntfTrafficExceed_oid));

    snmp_varlist_add_variable(&var_list,
        ifName_oid, OID_LENGTH(ifName_oid),
        ASN_OCTET_STR,
        (u_char *)alarm_info.if_info.ifname, strlen(alarm_info.if_info.ifname));
	
    snmp_varlist_add_variable(&var_list,
        ifIndex_oid, OID_LENGTH(ifIndex_oid),
        ASN_INTEGER,
        (u_char *)&alarm_info.if_info.if_index, sizeof(alarm_info.if_info.if_index));
	
    snmp_varlist_add_variable(&var_list,
        ifInputRate_oid, OID_LENGTH(ifInputRate_oid),
        ASN_OCTET_STR,
        (u_char *)alarm_info.if_info.if_rate.if_in_rate, strlen(alarm_info.if_info.if_rate.if_in_rate));
	
    snmp_varlist_add_variable(&var_list,
        ifOutputRate_oid, OID_LENGTH(ifOutputRate_oid),
        ASN_OCTET_STR,
        (u_char *)alarm_info.if_info.if_rate.if_out_rate, strlen(alarm_info.if_info.if_rate.if_out_rate));

    send_v2trap( var_list );
    snmp_free_varbind( var_list );

    return SNMP_ERR_NOERROR;
}
int
send_fhIntfRxBadPktExceed_trap( snmp_alarm_info_t alarm_info )
{
    netsnmp_variable_list  *var_list = NULL;
    const oid fhIntfRxBadPktExceed_oid[] = { 1,3,6,1,4,1,11408,11,1,2,3,2,1 };
    const oid ifName_oid[] = { 1,3,6,1,4,1,11408,11,1,2,2,0,0,1};
    const oid ifIndex_oid[] = { 1,3,6,1,4,1,11408,11,1,2,2,0,0,2};
    const oid ifInputError_oid[] = { 1,3,6,1,4,1,11408,11,1,2,2,0,0,10};
    const oid ifOutputError_oid[] = { 1,3,6,1,4,1,11408,11,1,2,2,0,0,11};


    snmp_varlist_add_variable(&var_list,
        snmptrap_oid, snmptrap_oid_len,
        ASN_OBJECT_ID,
        fhIntfRxBadPktExceed_oid, sizeof(fhIntfRxBadPktExceed_oid));

    snmp_varlist_add_variable(&var_list,
        ifName_oid, OID_LENGTH(ifName_oid),
        ASN_OCTET_STR,
        (u_char *)alarm_info.if_info.ifname, strlen(alarm_info.if_info.ifname));
	
    snmp_varlist_add_variable(&var_list,
        ifIndex_oid, OID_LENGTH(ifIndex_oid),
        ASN_INTEGER,
        (u_char *)&alarm_info.if_info.if_index, sizeof(alarm_info.if_info.if_index));
	
    snmp_varlist_add_variable(&var_list,
        ifInputError_oid, OID_LENGTH(ifInputError_oid),
        ASN_COUNTER64,
        (u_char *)&alarm_info.if_info.if_err.if_in_err, sizeof(alarm_info.if_info.if_err.if_in_err));
	
    snmp_varlist_add_variable(&var_list,
        ifOutputError_oid, OID_LENGTH(ifOutputError_oid),
        ASN_COUNTER64,
	(u_char *)&alarm_info.if_info.if_err.if_out_err, sizeof(alarm_info.if_info.if_err.if_out_err));

    send_v2trap( var_list );
    snmp_free_varbind( var_list );

    return SNMP_ERR_NOERROR;
}
int
send_fhPhysicalInterfaceDown_trap( snmp_alarm_info_t alarm_info )
{
    netsnmp_variable_list  *var_list = NULL;
    const oid fhPhysicalInterfaceDown_oid[] = { 1,3,6,1,4,1,11408,11,1,2,3,3,1 };
    const oid ifName_oid[] = { 1,3,6,1,4,1,11408,11,1,2,2,0,0,1,  };
    const oid ifIndex_oid[] = { 1,3,6,1,4,1,11408,11,1,2,2,0,0,2, };
    const oid ifInputError_oid[] = { 1,3,6,1,4,1,11408,11,1,2,2,0,0,10,  };
    const oid ifOutputError_oid[] = { 1,3,6,1,4,1,11408,11,1,2,2,0,0,11,  };

	BC_PT_FUN_TAG(BC_MODULE_SNMP);

    snmp_varlist_add_variable(&var_list,
        snmptrap_oid, snmptrap_oid_len,
        ASN_OBJECT_ID,
        fhPhysicalInterfaceDown_oid, sizeof(fhPhysicalInterfaceDown_oid));
    
    snmp_varlist_add_variable(&var_list,
        ifName_oid, OID_LENGTH(ifName_oid),
        ASN_OCTET_STR,
        (u_char *)alarm_info.if_info.ifname, strlen(alarm_info.if_info.ifname));
	
    snmp_varlist_add_variable(&var_list,
        ifIndex_oid, OID_LENGTH(ifIndex_oid),
        ASN_INTEGER,
        (u_char *)&alarm_info.if_info.if_index, sizeof(alarm_info.if_info.if_index));
	
    snmp_varlist_add_variable(&var_list,
        ifInputError_oid, OID_LENGTH(ifInputError_oid),
        /*ASN_COUNTER64*/ASN_INTEGER,
        (u_char *)&alarm_info.if_info.if_err.if_in_err, sizeof(alarm_info.if_info.if_err.if_in_err));
	
    snmp_varlist_add_variable(&var_list,
        ifOutputError_oid, OID_LENGTH(ifOutputError_oid),
        /*ASN_COUNTER64*/ASN_INTEGER,
        (u_char *)&alarm_info.if_info.if_err.if_out_err, sizeof(alarm_info.if_info.if_err.if_out_err));

    send_v2trap( var_list );
    snmp_free_varbind( var_list );

    return SNMP_ERR_NOERROR;
}

#if SNMP_PRJ_NAME_610A
#include "mBase.h"
#include "event/event_eth_port.h"
#include "mpapi.h"
#include "comm/lr_errors.h"

bc_boolean alarm_proc_dev_port(
											eventNotifyRes *resData, 
											struct event_bitmap event,
											struct mBase_client *client, 
											snmp_alarm_info_t alarm_info
										)
{
	struct mBase_param __param;  
	struct manageDeviceGetPortNameParam __request;  
	struct manageDeviceGetPortNameRes *__resData2;

	BC_PT_FUN_ENTER(BC_MODULE_SNMP);
	snmp_alarm_info_t __alarm_info;
	memset(&__alarm_info, 0, sizeof(snmp_alarm_info_t));
	memcpy(&__alarm_info, &alarm_info, sizeof(snmp_alarm_info_t));
	memset(&__alarm_info.cfg_info, 0, sizeof(snmp_alarm_cfg_t));
	
	memset(&__param, 0, sizeof(struct mBase_param));
	__request.ifindex = resData->triggerIndex;  
	__request.flgPrtId = TRUE;
	__param.privateParam = &__request;   
	__param.pparamLen = sizeof(struct manageDeviceGetPortNameParam);
	
	manageDeviceGetPortName(client, FLAG_VERSION | FLAG_SYNC, &__param);	

	if(__param.result == NULL)
	{   
		BC_PT_ERROR(BC_MODULE_SNMP,"manageDeviceGetPortName() error\n");
		return FALSE;
	}
	__resData2 = (struct manageDeviceGetPortNameRes *)__param.result->data;

	if(event.critical.event & ETHPORT_LINK)
	{
		BC_PT_EVENT(BC_MODULE_SNMP,"----------------------------------------------------------------\n");
		BC_PT_EVENT(BC_MODULE_SNMP,"Port:%d  Name:%s  EventType:%s  SubEventType:%s\n",
				__resData2->portId, __resData2->name, "ETHPORT_LINK", !(resData->eventCollect.ebits.critical.flags&ETHPORT_LINK)?"link down":"link up");
		BC_PT_EVENT(BC_MODULE_SNMP,"----------------------------------------------------------------\n");
		if(!(resData->eventCollect.ebits.critical.flags&ETHPORT_LINK))
		{
			BC_PT_FUN_TAG(BC_MODULE_SNMP);
			/*
			BC_PT_DBG_FUN(BC_MODULE_SNMP, "ifindex:%d, (ifname=%s  port_id=%d), EVENT_DEV_PORT.CRITICAL, ETHPORT_LINK,  flags=0x%x\n",  
			resData->triggerIndex, __resData2->name, __resData2->portId,  resData->eventCollect.ebits.critical.flags);  */
			__alarm_info.if_info.if_index = __resData2->portId;
			strcpy(__alarm_info.if_info.ifname, __resData2->name);
			__alarm_info.if_info.if_err.if_in_err = 0;
			__alarm_info.if_info.if_err.if_out_err = 0;
			__alarm_info.cfg_info.code = SNMP_ALARM_CODE_PHYSICAL_INTERFACE_DOWN;
			alarm_info.cfg_info.parse(&__alarm_info);
		}
	}
	else if(event.minor.event & ETHPORT_CRC_ERR)
	{ 
		BC_PT_FUN_TAG(BC_MODULE_SNMP);
	}   
	else if(event.minor.event & ETHPORT_RX_ERR)
	{ 
		BC_PT_FUN_TAG(BC_MODULE_SNMP);
	}   
	else if(event.prompt.event & ETHPORT_MIRROR)
	{ 
		BC_PT_FUN_TAG(BC_MODULE_SNMP);
	}  
	else if(event.prompt.event & ETHPORT_OFF)
	{ 
		BC_PT_FUN_TAG(BC_MODULE_SNMP);
	}  
	else if(event.prompt.event & ETHPORT_STATE_CHANGE)
	{ 
		BC_PT_FUN_TAG(BC_MODULE_SNMP);
	}  
	else if(event.prompt.event & ETHPORT_MODE_CHANGE)
	{ 
		BC_PT_FUN_TAG(BC_MODULE_SNMP);
	}  
	else if(event.prompt.event & ETHPORT_IF_LINK)
	{   
		BC_PT_DBG_FUN(BC_MODULE_SNMP, "ifindex:%d, (ifname=%s  port_id=%d), EVENT_DEV_PORT.PROMPT, ETHPORT_IF_LINK,  flags=0x%x\n",
							resData->triggerIndex,  __resData2->name, __resData2->portId,   resData->eventCollect.ebits.prompt.flags);   
	}
	
	BC_PT_FUN_LEAVE(BC_MODULE_SNMP);
}
#endif
