CFLAGS += -I $(TOPDIR)	\
		  -I $(BC_INC_DIR_COMMON)	\
		  -I $(BC_INC_DIR_COMMON)/error	\
		  -I $(BC_INC_DIR_COMMON)/modules	\
		  -I $(BC_INC_DIR_COMMON)/nouse	\
		  -I $(BC_INC_DIR_COMMON)/ipc	\
		  -I $(BC_INC_DIR_COMMON)/platform	\
		  -I $(BC_INC_DIR_COMMON)/print	\
		  -I $(BC_INC_DIR_COMMON)/vfs	\
		  -I $(BC_INC_DIR_COMMON)/log	\
		  -I $(BC_INC_DIR_COMMON)/util	\
		  -I $(BC_INC_DIR_COMMON)/message	\
		  -I $(BC_INC_DIR_MODULE)/system/baseinfo	\
		  -I $(BC_INC_DIR_MODULE)/system/ipc	\
		  -I $(BC_INC_DIR_MODULE)/system/platform	\
		  -I $(BC_INC_DIR_MODULE)/system/session	\
		  -I $(BC_INC_DIR_MODULE)/system/test	\
		  -I $(BC_INC_DIR_MODULE)/system/usermgmt	\
		  -I $(BC_INC_DIR_MODULE)/system/print	\
		  -I $(BC_INC_DIR_MODULE)/system/binchie	\
		  -I $(BC_INC_DIR_MODULE)/system/startup	\
		  -I $(BC_INC_DIR_MODULE)/system/filetrans	\
		  -I $(BC_INC_DIR_MODULE)/system/stats	\
		  -I $(BC_INC_DIR_PROJ)

OBJECT = bc_startup.o
			
obj-y += $(OBJECT)