CFLAGS += -I $(TOPDIR)	\
		  -I $(CLI_INC_DIR)/common	\
		  -I $(CLI_INC_DIR)/common/platform \
		  -I $(CLI_INC_DIR)/common/print \
		  -I $(CLI_INC_DIR)/common/util \
		  -I $(CLI_INC_DIR)/common/vfs \
		  -I $(CLI_INC_DIR)/module	\
		  -I $(CLI_INC_DIR)/module/filetrans \
		  -I $(CLI_INC_DIR)/core
		  
obj-y += filetrans/
obj-y += bc_cli_base.o
obj-y += bc_cli_cmds.o
obj-y += bc_cli_text.o