CFLAGS += -I $(TOPDIR)	\
		  -I $(BC_INC_DIR_COMMON)	\
		  -I $(BC_INC_DIR_COMMON)/error	\
		  -I $(BC_INC_DIR_COMMON)/modules	\
		  -I $(BC_INC_DIR_COMMON)/ipc	\
		  -I $(BC_INC_DIR_COMMON)/nouse	\
		  -I $(BC_INC_DIR_COMMON)/platform	\
		  -I $(BC_INC_DIR_COMMON)/print	\
		  -I $(BC_INC_DIR_COMMON)/vfs	\
		  -I $(BC_INC_DIR_COMMON)/log	\
		  -I $(BC_INC_DIR_COMMON)/util	\
		  -I $(BC_INC_DIR_COMMON)/message	\
		  -I $(BC_INC_DIR_PROJ)				\
		  -I $(MODULEDIR)/L2mc/drv		\
		  -I $(MODULEDIR)/L2mc/igmpsnp/util/inc	\
		  -I $(MODULEDIR)/L2mc/igmpsnp/mcast/inc
		  
		  
OBJECT = drv_chipname_mcast.o drv_mcast.o
			
obj-y += $(OBJECT)