CFLAGS += -I $(BC_INC_DIR)	\
		  -I $(BC_INC_DIR)/common	\
		  -I $(BC_INC_DIR)/common/error	\
		  -I $(BC_INC_DIR)/common/modules	\
		  -I $(BC_INC_DIR)/common/nouse	\
		  -I $(BC_INC_DIR)/common/ipc	\
		  -I $(BC_INC_DIR)/common/platform	\
		  -I $(BC_INC_DIR)/common/print	\
		  -I $(BC_INC_DIR)/common/vfs	\
		  -I $(BC_INC_DIR)/common/log	\
		  -I $(BC_INC_DIR)/common/util	\
		  -I $(BC_INC_DIR)/module/system/baseinfo	\
		  -I $(BC_INC_DIR)/module/system/ipc	\
		  -I $(BC_INC_DIR)/module/system/platform	\
		  -I $(BC_INC_DIR)/module/system/session	\
		  -I $(BC_INC_DIR)/module/system/log	\
		  -I $(BC_INC_DIR)/proj
		  
CFLAGS += -I $(SNMP_INC_DIR)	\
		  -I $(SNMP_INC_DIR)/module	\
		  -I $(SNMP_INC_DIR)/module/mib2/ip	\
		  -I $(SNMP_INC_DIR)/core	
		  
  
OBJECT = snmp_mib2_ipAddrTable.o snmp_mib2_ip.o
		
obj-y += $(OBJECT)
	