CFLAGS += -I $(TOPDIR)	\
		  -I $(CLI_INC_DIR)/common	\
		  -I $(CLI_INC_DIR)/common/platform \
		  -I $(CLI_INC_DIR)/common/print \
		  -I $(CLI_INC_DIR)/common/util \
		  -I $(CLI_INC_DIR)/common/vfs \
		  -I $(CLI_INC_DIR)/module	\
		  -I $(CLI_INC_DIR)/module/filetrans \
		  -I $(CLI_INC_DIR)/core
		  

obj-y += utili_avlt.o
obj-y += utili_bit.o
obj-y += utili_block.o
obj-y += utili_hash.o
obj-y += utili_ip_mac.o
obj-y += utili_list.o
obj-y += utili_rbt.o
obj-y += utili_string.o