CFLAGS += -I $(BC_INC_DIR)/common	\
		  -I $(BC_INC_DIR)/common/error	\
		  -I $(BC_INC_DIR)/common/modules	\
		  -I $(BC_INC_DIR)/common/nouse	\
		  -I $(BC_INC_DIR)/common/ipc	\
		  -I $(BC_INC_DIR)/common/platform	\
		  -I $(BC_INC_DIR)/common/print	\
		  -I $(BC_INC_DIR)/common/vfs	\
		  -I $(BC_INC_DIR)/common/log	\
		  -I $(BC_INC_DIR)/common/util	\
		  -I $(BC_INC_DIR)/common/message	\
		  -I $(BC_INC_DIR)/module/system/cli	\
		  -I $(BC_INC_DIR)/proj

CFLAGS += -I $(CLI_INC_DIR)	
		  
  
OBJECT = bc_cli_cmd_ipc_debug.o

obj-y += $(OBJECT)